# ~~~~~ CONNECTION PARAMETERS ~~~~~

[connection]

# ----- Device Name / Port -----
# Specify either device name for auto port detection or hardcode port.
# Will auto detect by name if no port specified
device_name = "/dev/ttyAMA0"
port = ""